### ISSUE TITLE
Parameter prompt

### ISSUE THREAD

**Issue by jasonkuhrt** [jasonkuhrt/molt#9]
#### Perceived Problem

Sometimes as a CLI author you want your users to be able to give parameters up front or enter into an interactive prompt to complete the fields.

#### Ideas / Proposed Solution(s)

Here is a before/after sketch showing how this feature could look like. The `before` is based on real world code.

##### Before

```ts
import { instantiateTemplate } from './__helpers__'
import { Command } from '@molt/command'
import inquirer from 'inquirer'
import { z } from 'zod'

interface Input {
  name: string
  description: string
  fly: boolean
}

main().catch((error) => {
  //eslint-disable-next-line
  console.log(error.message)
  process.exit(1)
})

async function main() {
  /**
   * Input
   */

  const args = Command.parameter(`name`, z.string().optional())
    .parameter(`description`, z.string().optional())
    .parameter(`fly`, z.boolean().optional())
    .parse()

  const input: Input = await inquirer.prompt(
    [
      {
        name: `name`,
        message: `What is the name of this application`,
      },
      {
        name: `description`,
        message: `What is the description of this application`,
      },
      {
        name: `fly`,
        message: `Is this application being deployed to Fly?`,
        type: `confirm`,
        default: true,
      },
    ],
    args
  )

  /**
   * Generator
   */

  await instantiateTemplate({
    description: input.description,
    name: input.name,
    template: {
      kind: `app`,
      fly: input.fly,
    },
  })
}
```

##### After

```ts
import { instantiateTemplate } from './__helpers__'
import { Command } from '@molt/command'
import input from 'inquirer/lib/prompts/input'
import { z } from 'zod'

main().catch((error) => {
  //eslint-disable-next-line
  console.log(error.message)
  process.exit(1)
})

async function main() {
  /**
   * Input
   */

  const args = Command()
    .parameter(`name`, {
      schema: z.string(),
      description: `The name of the app.`,
      prompt: true,
    })
    .parameter(`description`, {
      schema: z.string(),
      description: `A brief description of the app. Used for the npm package.json description field.`,
      optional: true,
      prompt: true,
    })
    .parameter(`fly`, {
      schema: z.boolean(),
      description: `Whether or not the app is being deployed to fly.`,
      default: true,
      prompt: true,
    })
    .parse()

  /**
   * Generator
   */

  await instantiateTemplate({
    description: input.description,
    name: input.name,
    template: {
      kind: `app`,
      fly: input.fly,
    },
  })
}
```

And here is a sketch of how the prompt could look like in terminal:

```
1/3  name
     The name of the app.
     ❯ skunk

2/3  description
     A brief description of the app. Used for the 
     npm package.json description field.
     ❯ Blah blah blah

3/3  fly
     Whether or not the app is being deployed to fly.
     ❯ yes / no
```

And an alternative sketch:

```

	 Question           Description
     --------           -----------
1/3  name				The name of the app.
     skunk

2/3  description		A brief description of the app. Used for the npm package.json description field.
     Blah blah blah

3/3  fly 				Whether or not the app is being deployed to fly.
     yes / no

```

#### Tasks

- [x] Show parameter name/description/prompt before/above input
- [x] Show gutter progress indicator
- [x] Settings to control default prompt behaviour https://github.com/jasonkuhrt/molt/commit/570feddecf548d1585f94ffdb363799709f6873c
- [x] UI for booleans
- [x] UI for enums

**Comment by jasonkuhrt** [comment]
Here is a before/after sketch showing how this feature could look like. The `before` is based on real world code.

### Before

```ts
import { instantiateTemplate } from './__helpers__'
import { Command } from '@molt/command'
import inquirer from 'inquirer'
import { z } from 'zod'

interface Input {
  name: string
  description: string
  fly: boolean
}

main().catch((error) => {
  //eslint-disable-next-line
  console.log(error.message)
  process.exit(1)
})

async function main() {
  /**
   * Input
   */

  const args = Command.parameter(`name`, z.string().optional())
    .parameter(`description`, z.string().optional())
    .parameter(`fly`, z.boolean().optional())
    .parse()

  const input: Input = await inquirer.prompt(
    [
      {
        name: `name`,
        message: `What is the name of this application`,
      },
      {
        name: `description`,
        message: `What is the description of this application`,
      },
      {
        name: `fly`,
        message: `Is this application being deployed to Fly?`,
        type: `confirm`,
        default: true,
      },
    ],
    args
  )

  /**
   * Generator
   */

  await instantiateTemplate({
    description: input.description,
    name: input.name,
    template: {
      kind: `app`,
      fly: input.fly,
    },
  })
}
```

### After

```ts
import { instantiateTemplate } from './__helpers__'
import { Command } from '@molt/command'
import input from 'inquirer/lib/prompts/input'
import { z } from 'zod'

main().catch((error) => {
  //eslint-disable-next-line
  console.log(error.message)
  process.exit(1)
})

async function main() {
  /**
   * Input
   */

  const args = Command()
    .parameter(`name`, {
      schema: z.string(),
      description: `The name of the app.`,
      prompt: true,
    })
    .parameter(`description`, {
      schema: z.string(),
      description: `A brief description of the app. Used for the npm package.json description field.`,
      optional: true,
      prompt: true,
    })
    .parameter(`fly`, {
      schema: z.boolean(),
      description: `Whether or not the app is being deployed to fly.`,
      default: true,
      prompt: true,
    })
    .parse()

  /**
   * Generator
   */

  await instantiateTemplate({
    description: input.description,
    name: input.name,
    template: {
      kind: `app`,
      fly: input.fly,
    },
  })
}
```

**Comment by Phoscur** [comment]
Hi @jasonkuhrt, just watched your introduction video!
Last week I implemented a little [(y)args-env-storage-prompter for oryx-macro-hax](https://github.com/Phoscur/oryx-macro-hax/blob/7-add-prompts/src/main.ts) (Currently I don't have too many arguments, but I think there are going to be many more when I merge the project with a related one. Currently precedence is `ENV > storage > args > prompt`, I guess I should rethink that.
```
oryx-macro-hax (npm start) <cmd> [args]

Commands:
  oryx-macro-hax get [layoutID]      - download a layout
  oryx-macro-hax process [username]  - apply macros/<username>.ts
```
I am very unhappy about type safety though. I think I should try to refactor it to `@molt/command` instead of `yargs`, as I was already about to add `zod` anyways! I'll try that soon.. (and zodify `prompts`?).

What are your thoughts about `prompts` instead of `inquirer` and what about `node-persist`, can it be plugged in?
I hope this is the right place to reference this, I don't have a clear idea for a new issue yet ;)

**Comment by jasonkuhrt** [comment]
@Phoscur I'm not sure about what your exact needs are but, but in general that toolset you references it something I would like Molt to be able to replace, do better, be more type safe specifically.

If you do give Molt a try, I'd definitely be responsive to issues you hit while trying to adopt it.

> can it be plugged in?

For node-persist, I'm not sure what you're looking for.
